name: clusterorbit_mobile
description: ClusterOrbit mobile client scaffold.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  sqflite: ^2.3.3
  path_provider: ^2.1.4
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  sqflite_common_ffi: ^2.3.4
  sqlite3_flutter_libs: ^0.5.0

flutter:
  uses-material-design: true
  assets:
    - .env